config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
RedmineApp::Application.routes.draw do

  scope "/projects/:project_id" do
    resources :tb_polls do 
      post "vote", on: :member
    end
  end
end

app/models/tb_poll.rb
class TbPoll < ActiveRecord::Base
  unloadable

  belongs_to :author, class_name: "User", foreign_key: "author_id"
  belongs_to :project
  attr_accessible :no, :question, :yes

  validates :project, :author, presence: true
  
  def vote(answer)
    increment(answer == "yes" ? :yes : :no)
  end
  
end

app/controllers/tb_polls_controller.rb
class TbPollsController < ApplicationController
  unloadable
  
  respond_to :html, :json
  respond_to :js, only: [:show, :new, :create, :edit, :update, :destroy, :vote]

  before_filter :find_project_by_project_id
  before_filter :find_tb_poll, only: [:show, :edit, :update, :destroy, :vote]
  before_filter :authorize

  include SortHelper
  helper :sort

  def index
    sort_init "updated_at"
    sort_update %w(question yes no created_at updated_at)
    @tb_poll_pages, @tb_polls = paginate TbPoll.where(project_id: @project).order(sort_clause)
    respond_with @tb_polls
  end

  def show
    respond_with @tb_poll
  end

  def new
    @tb_poll = TbPoll.new
    respond_with @tb_poll
  end

  def edit
    respond_with @tb_poll
  end

  def create
    @tb_poll = TbPoll.new(params[:tb_poll])
    @tb_poll.project = @project
    @tb_poll.author = User.current
    if @tb_poll.save && !request.xhr?
      flash[:notice] = l(:label_tb_poll_created)
    end
    respond_with @tb_poll
  end

  def update
    if @tb_poll.update_attributes(params[:tb_poll]) && !request.xhr?
      flash[:notice] = l(:label_tb_poll_updated)
    end
    respond_with @tb_poll
  end

  def destroy
    @tb_poll.destroy
    flash[:notice] = l(:label_tb_poll_deleted) unless request.xhr?
    respond_with @tb_poll, location: tb_polls_path
  end

  # Override url/path convenience methods options to include project
  def url_options
    super.reverse_merge project_id: @project
  end

  
  def vote
  @tb_poll.vote params[:answer]
  flash[:notice] = "Voted #{params[:answer]}" if @tb_poll.save && !request.xhr?
    respond_with(@tb_poll) do |format|
      format.js { render action: :show }
    end
  end

  def vote_poll_path
    poll = TbPoll.find(params[:id])
    poll.vote(params[:answer])
    if poll.save
      flash[:notice] = 'Vote saved. TbPoll'
    end
    redirect_to :action => 'index'
  end
  
  private
  def find_tb_poll
    @tb_poll = TbPoll.find(params[:id])
    render_404 unless @tb_poll.project_id == @project.id
  rescue ActiveRecord::RecordNotFound
    render_404
  end
end

app/helpers/tb_polls_helper.rb
module TbPollsHelper
end

app/views/tb_polls/_form.html.erb
<%= labelled_form_for(@tb_poll) do |f| %>
  <%= error_messages_for "tb_poll" %>

  <div class="box tabular">
    <p><%= f.text_field :question %></p>
    <p><%= f.number_field :yes %></p>
    <p><%= f.number_field :no %></p>
  </div>

  <p class="buttons">
    <%= f.submit %>
  </p>
<% end %>

app/views/tb_polls/_form.js.erb
<%= labelled_form_for(@tb_poll, remote: true) do |f| %>
  <%= error_messages_for "tb_poll" %>

  <div class="box tabular">
    <p><%= f.text_field :question %></p>
    <p><%= f.number_field :yes %></p>
    <p><%= f.number_field :no %></p>
  </div>

  <p class="buttons">
    <%= f.submit %>
    <%= submit_tag l(:button_cancel), onclick: "hideModal(this);", type: "button" %>
  </p>
<% end %>

app/views/tb_polls/_tb_poll.html.erb
<tr id="<%= dom_id tb_poll %>" class="<%= cycle "odd", "even" %>">
  <td><%= tb_poll.question %></td>
  <td><%= tb_poll.yes %></td>
  <td><%= tb_poll.no %></td>
  <td><%= authoring tb_poll.created_at, tb_poll.author %>.</td>
  <td><%= l(:label_updated_time, time_tag(tb_poll.updated_at)).html_safe %>.</td>
  <td class="buttons">
    <%= link_to l(:button_show), tb_poll, remote: true %>
    <%= link_to l(:button_edit), edit_tb_poll_path(tb_poll), class: "icon icon-edit", remote: true %>
    <%= link_to l(:button_delete), tb_poll, method: :delete, data: { confirm: l(:text_are_you_sure) }, class: "icon icon-del", remote: true %>
  </td>
</tr>

app/views/tb_polls/create.js.erb
<% if @tb_poll.valid? %>
  hideModal();
  if ($(".tb_polls.list").length) {
    $(".nodata").hide();
    $(".tb_polls").show();
    $("<%= j render(@tb_poll, formats: [:html]) %>").prependTo(".tb_polls tbody").effect("highlight");
  } else {
    window.location.href = "<%= url_for @tb_poll %>";
  }
<% else %>
  $("#errorExplanation").remove();
  $("<%= j error_messages_for("tb_poll") %>").prependTo("#new_tb_poll");
<% end %>

app/views/tb_polls/destroy.js.erb
$("#<%= dom_id @tb_poll %>").fadeOut();

app/views/tb_polls/edit.html.erb
<h2><%= link_to l(:label_tb_poll_plural), tb_polls_path %>
  &#187; <%= l(:label_tb_poll_edit) %></h2>

<%= render "form" %>

<% html_title l(:label_tb_poll_edit) -%>

app/views/tb_polls/edit.js.erb
<% html = capture do %>
  <h3 class="title"><%= l(:label_tb_poll_edit) %></h3>
  <%= render partial: "form" %>
<% end %>

$("#ajax-modal").html("<%= j html %>").find(".box").css("z-index", "auto");
showModal("ajax-modal", "600px");

app/views/tb_polls/index.html.erb
<div class="contextual">
  <%= link_to l(:label_tb_poll_new), new_tb_poll_path, class: "icon icon-add", remote: true %>
</div>

<h2><%= l(:label_tb_poll_plural) %></h2>

<% if @tb_polls.empty? %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<div class="autoscroll">
  <table class="list tb_polls" style="<%= "display: none;" if @tb_polls.empty? %>">
    <thead>
      <tr>
        <%= sort_header_tag "question", caption: l(:field_question) %>
        <%= sort_header_tag "yes", caption: l(:field_yes) %>
        <%= sort_header_tag "no", caption: l(:field_no) %>
        <%= sort_header_tag "created_at", caption: l(:field_created_on), default_order: "desc" %>
        <%= sort_header_tag "updated_at", caption: l(:field_updated_on), default_order: "desc" %>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render @tb_polls %>
    </tbody>
  </table>
</div>

<p class="pagination"><%= pagination_links_full @tb_poll_pages %></p>

<% html_title l(:label_tb_poll_plural) -%>

app/views/tb_polls/new.html.erb
<h2><%= link_to l(:label_tb_poll_plural), tb_polls_path %>
  &#187; <%= l(:label_tb_poll_new) %></h2>

<%= render "form" %>

<% html_title l(:label_tb_poll_new) -%>

app/views/tb_polls/new.js.erb
<% html = capture do %>
  <h3 class="title"><%= l(:label_tb_poll_new) %></h3>
  <%= render partial: "form" %>
<% end %>

$("#ajax-modal").html("<%= j html %>").find(".box").css("z-index", "auto");
showModal("ajax-modal", "600px");

app/views/tb_polls/show.html.erb
<div class="contextual">
  <%= link_to l(:label_tb_poll_edit), edit_tb_poll_path(@tb_poll), class: "icon icon-edit", remote: true %>
</div>

<h2><%= link_to l(:label_tb_poll_plural), tb_polls_path %>
  &#187; <%= l(:label_tb_poll) %></h2>

<div class="box">
<p>
  <b>Question:</b>
  <%= @tb_poll.question %>
</p>
<p>
  <b>Yes:</b>
  <%= @tb_poll.yes %>
</p>
<p>
  <b>No:</b>
  <%= @tb_poll.no %>
</p>
</div>
<div class="box">
	<p>
	  <b>Vote:</b>
	  <%= link_to "Yes", vote_poll_path(@tb_poll, answer: "yes"), method: :post %> |
	  <%= link_to "No", vote_poll_path(@tb_poll, answer: "no"), method: :post %>
	</p>
</div>

<% html_title l(:label_tb_poll) -%>

app/views/tb_polls/show.js.erb
<% html = capture do %>
  <h3 class="title"><%= l(:label_tb_poll) %></h3>
  <div class="box">
    <p>
      <b>Question:</b>
      <%= @tb_poll.question %>
    </p>
    <p>
      <b>Yes:</b>
      <%= @tb_poll.yes %>
    </p>
    <p>
      <b>No:</b>
      <%= @tb_poll.no %>
    </p>
  </div>

  <p class="buttons">
    <%= submit_tag l(:button_cancel), onclick: "hideModal(this);", type: "button" %>
  </p>
<% end %>

$("#ajax-modal").html("<%= j html %>").find(".box").css("z-index", "auto");
showModal("ajax-modal", "600px");

app/views/tb_polls/update.js.erb
<% if @tb_poll.valid? %>
  hideModal();
  if ($(".tb_polls.list").length) {
    $("#<%= dom_id @tb_poll %>").replaceWith("<%= j render(@tb_poll) %>");
    $("#<%= dom_id @tb_poll %>").effect("highlight");
  } else {
    window.location.href = "<%= url_for @tb_poll %>";
  }
<% else %>
  $("#errorExplanation").remove();
  $("<%= j error_messages_for("tb_poll") %>").prependTo("#edit_tb_poll_<%= @tb_poll.id %>");
<% end %>